version: "2.1"
volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=truenas.osborn.xyz,rw
      device: ":/mnt/data/appdata/jellyfin"
  tv:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=truenas.osborn.xyz,rw
      device: ":/mnt/data/tv"
  movies:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=truenas.osborn.xyz,rw
      device: ":/mnt/data/movies"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - config:/config
      - tv:/data/tvshows
      - movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
