version: "2.1"
volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=truenas.osborn.xyz,rw
      device: ":/mnt/data/appdata/prowlarr"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
